name: Morpheus Test

on: 
  push:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: System info
      run: |
        uname -a
    - name: Configure and Build
      run: |
        chmod +x "${GITHUB_WORKSPACE}/setup_dut.sh"
        ${GITHUB_WORKSPACE}/setup_dut.sh
    - name: Test
      run: |
        cd "${GITHUB_WORKSPACE}/experiments/router/simple"
        tmux new-session -d -s morpheus 'sudo polycubed'
        sleep 30
        chmod +x router-simple-start.sh
        ./router-simple-start.sh -q
        