name: Morpheus Build

on: 
  push:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: System info
      run: |
        uname -a
    - name: Configure and Build
      run: |
        chmod +x "${GITHUB_WORKSPACE}/setup_dut.sh"
        ${GITHUB_WORKSPACE}/setup_dut.sh
    - name: Run
      run: |
        sudo timeout --preserve-status -s SIGINT 30 sudo polycubed